# Generated by Django 3.0.6 on 2020-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_emplyee_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee_details',
            name='current_profile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emplyee_details',
            name='degination',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emplyee_details',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emplyee_details',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emplyee_details',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
