# Generated by Django 3.0.6 on 2020-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201103_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee_details',
            name='resume',
            field=models.FileField(blank=True, default=3, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
