# Generated by Django 3.0.6 on 2020-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201103_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee_details',
            name='resume',
            field=models.FileField(blank=True, default='None', upload_to='uploads/'),
        ),
    ]
